import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TaskInput from "../components/TaskInput";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={inter.className}>
        <main className="mx-auto grid gap-4 p-4 lg:w-4/5 xl:w-3/5 2xl:w-2/5">
          <TaskInput />
          {children}
        </main>
      </body>
    </html>
  );
}
